apiVersion: v2
name: tarot
version: 0.4.0
description: Dynamic workflow composition system using mystical card-based architecture
home: https://github.com/runik-platform
sources:
  - https://github.com/runik-platform/runik-platform
annotations:
  artifacthub.io/license: AGPL-3.0-only
maintainers:
  - name: namen malkav
    email: namenmalkav@gmail.com
  - name: laaledesiempre
    email: laaledesiempre@disroot.org
